id: AB74CC0CC
title: Prayer for the Long Life Dodrupchen Rinpoche
type: translation
pechas:
- I1E1076B8
- I5C90540D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:07.642452
  last_modified_at: 2023-01-04 11:48:07.642458
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I1E1076B8/993E: 45D5
  I5C90540D/3055: 45D5
